
##################################################################################################################
#    ██╗     ██╗   ██╗███╗   ██╗ █████╗ ██████╗     ███████╗██████╗ ███████╗███████╗ ██████╗ █████╗ ███╗   ███╗  #
#    ██║     ██║   ██║████╗  ██║██╔══██╗██╔══██╗    ██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗████╗ ████║  #
#    ██║     ██║   ██║██╔██╗ ██║███████║██████╔╝    █████╗  ██████╔╝█████╗  █████╗  ██║     ███████║██╔████╔██║  #
#    ██║     ██║   ██║██║╚██╗██║██╔══██║██╔══██╗    ██╔══╝  ██╔══██╗██╔══╝  ██╔══╝  ██║     ██╔══██║██║╚██╔╝██║  #
#    ███████╗╚██████╔╝██║ ╚████║██║  ██║██║  ██║    ██║     ██║  ██║███████╗███████╗╚██████╗██║  ██║██║ ╚═╝ ██║  #
#    ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝  #
#                                          Made By Magas8                                                        #
##################################################################################################################




##################################################
#                   Messages                     #
##################################################
freecam-mode-on-success: "&8&l[&2&l!&8&l] &7Successfully went into FreeCam mode."
freecam-mode-off-success: "&8&l[&2&l!&8&l] &7Successfully went back to your previous location."
too-many-arguments-message: "&8&l[&c&l!&8&l] &7Too many arguments. Usage: &5/freecam"
cannot-use-commands-message: "&8&l[&c&l!&8&l] &7You cant use commands while in FreeCam mode."
maximum-distance-reached-message: "&8&l[&c&l!&8&l] &7You have reached the maximum allowed distance."
no-permission-message: "&8&l[&c&l!&8&l] &7You don't have permission to use this command."
freecam-not-player: "&8&l[&c&l!&8&l] &7Only players can use this command!"
freecam-spectate-teleport: "&8&l[&c&l!&8&l] &7You cant teleport when you are at freecam mode."
freecam-cant-open-inv: "&8&l[&c&l!&8&l] &7You cant interact with inventories when you are on freecam mode"
freecam-cant-drop-items: "&8&l[&c&l!&8&l] &7You cant drop items when you are on freecam mode"
freecam-action-bar: "&8&l[&b&lFreeCam&8&l] &c&l%seconds% &8seconds left."
freecam-canceled: "&8&l[&c&l!&8&l] &cYour freecam was cancelled"
freecam-max-distance-reach: "&8&l[&c&l!&8&l] &7You have reached the max distance of Blocks"
freecam-reload: "&8&l[&c&l!&8&l] &7Config reloaded Successfully"
freecam-no-use: "&8&l[&c&l!&8&l] &7You are not in freecam mode"
on-freecam-cmd: "&8&l[&c&l!&8&l] &7This command is not allowed during FreeCam mode.             &8&l[&c&l!&8&l] &7Type &5/freecam stop &7to cancel FreeCam mode."
already-freecam: "&8&l[&c&l!&8&l] &7You are in freecam mode!"
freecam-tp-while-in-freecam: "&8&l[&c&l!&8&l] &7You can't tp to someone when in freecam"
##################################################
#                 Freecam Settings               #
##################################################
#Use -1 for unlimited freecam period
freecam-period: 30
#Use -1 for unlimited freecam distance
freecam-max-distance: 120
freecam-whitelisted-commands:
  - /freecam stop
##################################################
#             LunarFreecam Perms                 #
##################################################
# freecam.use Allow players to use /freecam
# freecam.reload Allow players to reload the plugin