
##################################################################################################################
#    ██╗     ██╗   ██╗███╗   ██╗ █████╗ ██████╗     ███████╗██████╗ ███████╗███████╗ ██████╗ █████╗ ███╗   ███╗  #
#    ██║     ██║   ██║████╗  ██║██╔══██╗██╔══██╗    ██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗████╗ ████║  #
#    ██║     ██║   ██║██╔██╗ ██║███████║██████╔╝    █████╗  ██████╔╝█████╗  █████╗  ██║     ███████║██╔████╔██║  #
#    ██║     ██║   ██║██║╚██╗██║██╔══██║██╔══██╗    ██╔══╝  ██╔══██╗██╔══╝  ██╔══╝  ██║     ██╔══██║██║╚██╔╝██║  #
#    ███████╗╚██████╔╝██║ ╚████║██║  ██║██║  ██║    ██║     ██║  ██║███████╗███████╗╚██████╗██║  ██║██║ ╚═╝ ██║  #
#    ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝  #
#                                          Made By Magas8                                                        #
##################################################################################################################




##################################################
#                   Messages                     #
##################################################
too-many-arguments: "&8&l[&c&l!&8&l] &7Too many arguments. Usage: &5/freecam"
invalid-use: "&8&l[&c&l!&8&l] &7Invalid use. Usage: &5/freecam"
no-permission: "&8&l[&c&l!&8&l] &7You don't have permission to use this command."
spectator: "&8&l[&c&l!&8&l] &7You cannot enter freecam in spectator mode."
freecam-not-player: "&8&l[&c&l!&8&l] &7Only players can use this command!"
freecam-illegal: "&8&l[&c&l!&8&l] &7You may not do this while in freecam mode."
freecam-cancelled: "&8&l[&c&l!&8&l] &cYou were kicked out of freecam mode since your npc was hurt."
reload: "&8&l[&c&l!&8&l] &7Config reloaded Successfully"
##################################################
#             LunarFreecam Perms                 #
##################################################
# freecam.use Allow players to enter freecam
# freecam.reload Allow players to reload the plugin