name: LunarFreeCam
description: A simple freecam plugin for all types of servers
authors: [ magas8, OliTheHoodieBoi ]
version: ${project.version}
main: lunarfreecam.freecam.Main
api-version: 1.19
commands:
  freecam:
    usage: /freecam
    aliases: [ roam ]
    description: Used to activate freecam
permissions:
  freecam.use:
    default: true
    description: Allow players to use /freecam
  freecam.reload:
    default: op
    description: Allow Players to reload the plugin